### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES="language-gfm language-asciidoc"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx
  
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install languagetool; fi

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
